spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/oauth2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    initialization-mode: never # resource 에 있는 schema.sql 을 실행 (기본값: always, 생성안함: never)
  post-datasource:
    url: jdbc:mariadb://localhost:3308/post
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa: # DB 쿼리 작성 없이 코드로 쉽게 데이터 처리를 위함.
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #    hibernate:
  #      ddl-auto: none # 필요시 create 으로 변경후 사용
  main:
    allow-bean-definition-overriding: true # userDetailService 기존 스프링 제공 함수 안쓰고 정의 함수로 바꾸기 위한 설정
server:
  port: 8081 # 사용 포트
  tomcat:
    accesslog:
      enabled: true # access 로그 추가
    basedir: .
#  servlet:
#    session:
#      timeout: 10 # 세션 저장소(redis) 따로 지정 안할시 해당 설정으로 세션 시간 설정 / 기본 30분이며 60s 미만 설정시 60s로 된다.

oauth2:
  validity-seconds:
    access-token: 1800
    refresh-token: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus